# Arrays & Matrices

In [1]:
A = [ 1 2 3 4 ;
      5 6 7 8 ]

B = (1, )

C = 4

4

In [2]:
size( A )

(2, 4)

In [3]:
# size( B )

In [4]:
size( C )

()

In [5]:
typeof( A )

Matrix{Int64} (alias for Array{Int64, 2})

In [6]:
typeof( B )

Tuple{Int64}

In [7]:
typeof( C )

Int64

In [8]:
typeof( A ) == Matrix{Any}

false

In [9]:
supertype( supertype( typeof( A ) ) )

AbstractMatrix{Int64} (alias for AbstractArray{Int64, 2})

In [10]:
vec1 = [1,2,3]
vec2 = [4,5,6]
broadcast(abs, vec1 - vec2)

3-element Vector{Int64}:
 3
 3
 3

In [7]:
foo = [1 2 3 4];
display( foo[1:2] )
display( foo[3:4] )
max( size( zeros(4) )... )

2-element Vector{Int64}:
 1
 2

2-element Vector{Int64}:
 3
 4

4

In [1]:
_X_DOMAIN = [-2.0 +2.0; -2.0 +2.0]
_A_DOMAIN = [-0.5 +0.5; -0.5 +0.5]
_Q_DOMAIN = [_X_DOMAIN; _A_DOMAIN]
display( _Q_DOMAIN )

4×2 Matrix{Float64}:
 -2.0  2.0
 -2.0  2.0
 -0.5  0.5
 -0.5  0.5

In [3]:
5^4

625

In [4]:
using LinearAlgebra;

foo = zeros( (3,3,) );

function make_ID( matx )
    matx = Matrix(I, 3, 3)
    display( matx )
end

make_ID( foo )

display( foo )

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [2]:
"""
Blend two vectors by element
"""
function blend_alpha_of_A_into_B( alpha, A, B )
    return A*alpha + B*(1.0 - alpha)
end

A = [ 4, 4, 4 ]
B = [ 1, 1, 1 ]

blend_alpha_of_A_into_B( 0.25, A, B )


3-element Vector{Float64}:
 1.75
 1.75
 1.75

# Structs

## Struct Methods

In [11]:
"""
Demonstrates member functions (methods)
"""
mutable struct TinyStruct
    x::Float64 # ------ Operand 1
    y::Float64 # ------ Operand 2
    get_sum::Function # Summation method
    TinyStruct( x_, y_ ) = (
        TS = new();
        TS.x = x_;
        TS.y = y_;
        TS.get_sum = function ()
            return TS.x + TS.y;
        end;
        return TS;
    );
end

In [12]:
ts = TinyStruct(2,3)
ts.get_sum()

5.0