# Structs

In [ ]:
struct PointValue{N}
    pnt::Array{ Float64, N }
    val::Float64
    tre::KDTree{StaticArrays.SVector{N, Float64}, Euclidean, Float64}
end

# kd-Trees

In [13]:
using NearestNeighbors
data = rand(3, 10^4)

# Create trees
kdtree    = KDTree(data; leafsize = 10)
println( typeof( kdtree ) )
balltree  = BallTree(data, Minkowski(3.5); reorder = false)
brutetree = BruteTree(data)

kdtree.

KDTree{StaticArrays.SVector{3, Float64}, Euclidean, Float64}


BruteTree{StaticArrays.SVector{3, Float64}, Euclidean}
  Number of points: 10000
  Dimensions: 3
  Metric: Euclidean(0.0)
  Reordered: false

In [3]:
rand(3, 10^4)

3×10000 Matrix{Float64}:
 0.0732213  0.902221  0.27853    0.779282  …  0.301043  0.0627223  0.806034
 0.336336   0.576584  0.0485569  0.539493     0.721517  0.245838   0.463993
 0.0907351  0.691699  0.106335   0.925022     0.797657  0.0464356  0.907865

# Second Order Functions

In [1]:
function get_add_x( x )
    return function( y )
        x + y
    end
end

get_add_x (generic function with 1 method)

In [3]:
foo = get_add_x( 3 )
print( foo(4) )

7

# For Loop Syntax

In [7]:
n=3
for i in n:-1:1 # Counting down from `n` to 1, inclusive
    print( i, ',' )
end

3,2,1,

# Vectors (Python Lists)

In [12]:
foo = []

Any[]

In [13]:
append!( foo, 1 )
append!( foo, [2,3] )
append!( foo, [[]] )
append!( foo, [Vector{Any}()] )

display( foo )

5-element Vector{Any}:
 1
 2
 3
  Any[]
  Any[]

In [5]:
baz = zeros(3,3)
qub = [1,2,3]
baz[:,2] = qub
display( baz )

3×3 Matrix{Float64}:
 0.0  1.0  0.0
 0.0  2.0  0.0
 0.0  3.0  0.0

In [9]:
a = [1,2,3]
b = [4,5,6]
display( vcat(a,b) )
display( vcat(b,7) )

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

4-element Vector{Int64}:
 4
 5
 6
 7

## Iterate Over Vector

In [2]:
bar = [1,2,3]
for elem in bar
    print( elem, ',' )
end

1,2,3,

# Scope

In [4]:
if true
    a = 1
else
    a = 2
end
print(a)

1

# Arrays

In [11]:
repeat([4],4)

4-element Vector{Int64}:
 4
 4
 4
 4